apiVersion: experimantal.giantswarm.com/v1
kind: Ghost
metadata:
  name: ghost-1
  namespace: ghost-test-1
spec:
  url: "ghost-1.kube.thisone.rocks"
  mail:
    from: '"Custom Name" <myemail@address.com>'
    service:
      type: Sparkpost
      auth:
        user: SMTP_Injection
        pass:
  database:
    client: sqlite3
