apiVersion: experimantal.giantswarm.com/v1
kind: Ghost
metadata:
  name: ghost-2
  namespace: ghost-another-test
spec:
  # url: "ghost-2.some.other.url"
  mail:
    from: '"Custom Name" <myemail@address.com>'
    service:
      type: Sparkpost
      auth:
        user: SMTP_Injection
        pass:
  database:
    client: sqlite3
